#!/usr/bin/env bash
# Configure haproxy to work as a load balancer for two servers
apt-get -y update
sudo apt-get -y install haproxy

backend="
backend web-backend
   balance roundrobin
   server web1 54.87.237.76:80 check
   server web2 54.83.130.208:80 check"
frontend="
frontend http
   bind *:80
   mode http

   default_backend web-backend"
echo "ENABLED=1" >> /etc/default/haproxy
echo "$frontend" >> /etc/haproxy/haproxy.cfg
echo "$backend" >> /etc/haproxy/haproxy.cfg
service haproxy restart
