#!/usr/bin/env bash
# This script displays Best School 9 times and hi on the 9th loop

i=0
while [ $i -le 9 ];
do
	i=$((i+1))
	if [ $i -eq 9 ]; then
		echo "Hi"
		continue
	fi
	echo "Best School"
done
