#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration,displays Best School for the other iterations

i=0
while [ $i -le 9 ];
do
	i=$((i+1))
	if [ $i -eq 4 ]; then
		echo "bad luck"
		continue
	fi
	if [ $i -eq 8 ]; then
                echo "bad luck"
                continue
        fi
	echo "Best School"
done
